### ISSUE TITLE
How do I run this code locally?

### ISSUE THREAD

**Issue by VinayakTekade** [jhackshaw/tspvis#15]
Hello,
I'm a beginner at this. Could you please explain to me how do I run this code locally?

**Comment by jhackshaw** [comment]
Sure! First you'll need to install node js if you haven't. I recommend [nvm](https://github.com/nvm-sh/nvm).

Than, from a command line, the following steps should help. I have not tested on windows, but it should work.
```
npm install
npm run develop
```

Please let me know how it goes.

**Comment by VinayakTekade** [comment]
When I run `npm run develop` after installing the dependencies. I'm getting these errors.
![image](https://user-images.githubusercontent.com/39454332/151748929-500a8ed7-f550-47a7-b68a-e13aa0004a44.png)

It seems like a file named `page-data.json` is missing and causing these errors. What shall I do to fix it?

**Comment by jhackshaw** [comment]
I do need to do some dependency upgrades, but there are a number of breaking changes in the gatsby dependencies. I just cloned the repo from scratch and it's working, can you give node version and OS?

**Comment by VinayakTekade** [comment]
Hi @jhackshaw I'm on Windows 11 21H2 Build 22000.675 and the node version is v16.15.0.

**Comment by Sudarshan-Navale** [comment]
Hi @jhackshaw I'm also facing the same issue as @VinayakTekade. could you please help me here. I'm using Win 10 and my node version is 16.14.2.

**Comment by Rajabov-Guru** [comment]
@VinayakTekade It's all about deck.gl. You need to update the version and register layers in props, not in children. It works for me

**Comment by jhackshaw** [comment]
Hey @rotemdan , this is fantastic thanks for taking a look! I would absolutely be willing to review a pull request with these changes.
