### ISSUE TITLE
convexHull Pseudocode

### ISSUE THREAD

**Issue by MohmedAAK** [jhackshaw/tspvis#6]
i am trying to re implement the convexHull algorithm in python that exist here but i had problems with understanding the algorithm insertion part , i already implemented  that part that create convex Hull of the shape based on choosing the leftmost point 
so if there is  Pseudo-code for the algorithm , it would be perfect or the name of the heuristic insertion algorithm would be nice.

thanks for such effort to put all these algorithms on live website for education.

**Comment by MohmedAAK** [comment]
oh thanks i found it on the website itself

In essence, convexHull Pseudocode ,the steps are:

    1-)Determine the leftmost point
    2-)Continually add the most counterclockwise point until the convex hull is formed
    3-)For each remaining point p, find the segment i => j in the hull that minimizes cost(i -> p) + cost(p -> j) - cost(i -> j)
    4-)Of those, choose p that minimizes cost(i -> p -> j) / cost(i -> j)
    5-)Add p to the path between i and j
    6-)Repeat from #3 until there are no remaining points

**Comment by Apollyon094** [comment]
The algorithm used for the convex hull part is a Graham scan. I suggest if implementing you use a different algorithm such as the Kirkpatrick-Seidel algorithm which is much faster.
